### ISSUE TITLE
What What?

### ISSUE THREAD

**Issue by D-Land** [valleyjo/orgman#88]
On event:
- [x] should we set self_submit_* to false by default on the schema
- [x] should we be setting semester in an after create hook?

On attendance:
- [x] should we set present and excused to false by default on the schema

**Comment by valleyjo** [comment]
For event:
for self_submit_* I don't think it matters if it's nil or false at the moment. but we could probably set them to false to default if you feel that's best practice.

yes

For Attendance:
Probably. You should take a look at the Attendance::EventController#create to see how attendances are created (better to see than have me give a bad explanation).
